### ISSUE TITLE
Webpack has compiled the call to axios adapters wrongly

### ISSUE THREAD

**Issue by tmoitie** [js-data/js-data-http#12]
https://github.com/js-data/js-data-http/blob/master/dist/js-data-http.js#L790-L794

The code on line 790 and 794 should be different, but instead both call the same reference (The XHR adapter). It means that any calls to js-data-http in NodeJS fail.

I have tried to recompile the library but I'm getting a "Unexpected reserved word" failure - looks like I can't get the babel-loader to work properly on my end.

**Comment by jmdobry** [comment]
I am investigating.

**Comment by analytik** [comment]
I think I might be experiencing a related issue. Using node.js 4.1.1.

Module `19` is defined as ```/* 19 */
/***/ function(module, exports) {

	/* (ignored) */

/***/ },```

but then since it's used like this:
```	    function lib$es6$promise$asap$$attemptVertex() {
	      try {
	        var r = require;
	        var vertx = __webpack_require__(19);
			  console.log(vertx);
	        lib$es6$promise$asap$$vertxNext = vertx.runOnLoop || vertx.runOnContext;
	        return lib$es6$promise$asap$$useVertxTimer();
	      } catch(e) {
	        return lib$es6$promise$asap$$useSetTimeout();
	      }
	    }```
both `vertx.runOnLoop` and `vertx.runOnContext` are `undefined`, and I'm getting this error:
```TypeError: lib$es6$promise$asap$$vertxNext is not a function
    at d:\project\node_modules\js-data-http\dist\js-data-http.js:1467:10
    at asap (d:\project\node_modules\js-data-http\dist\js-data-http.js:1427:12)
    at lib$es6$promise$promise$$Promise.then (d:\project\node_modules\js-data-http\dist\js-data-http.js:2268:12)
    at DSHttpAdapter.axios [as http] (d:\project\node_modules\js-data-http\dist\js-data-http.js:471:24)
    at DSHttpAdapter.HTTP (d:\project\node_modules\js-data-http\dist\js-data-http.js:270:20)
    at DSHttpAdapter.GET (d:\project\node_modules\js-data-http\dist\js-data-http.js:281:20)
    at DSHttpAdapter.find (d:\project\node_modules\js-data-http\dist\js-data-http.js:320:21)
    at d:\project\node_modules\js-data\dist\js-data-debug.js:4612:46
    at process._tickCallback (node.js:356:9)```

I am using js-data-rethinkdb successfully, but then I tried added js-data-http for another model, and I get the above error when I try a simple `SomeModel.find(someId).then(...)`.

This seems to be a (relatively) common problem with vertx and webpack, it seems? https://github.com/webpack/webpack/issues/353

**Comment by jmdobry** [comment]
There are currently problems with getting js-data-http to run on Node.

**Comment by analytik** [comment]
Ah, thanks for the confirmation. I'm still too new to the whole ecosystem out to be of any actual help, but I'll be glad to help with testing whenever something is ready.

**Comment by jmdobry** [comment]
Fixed in 3.0.0-alpha.1. Published `js-data-http-node` to NPM which works on Node.js, while `js-data-http` only works in the browser.

**Comment by SystemParadox** [comment]
Ugh. Why the separate package? Surely there is a better way to fix this? What's actually the issue here?

**Comment by jmdobry** [comment]
Perhaps there's a better way, but it might involve going farther down the webpack rabbit hole than I had time for. Maybe some of your free time will find a way where mine couldn't.

**Comment by SystemParadox** [comment]
I've started looking into this, but I'm a little confused what the actual problem is. Is this due to:

- a bug in webpack?
- a configuration issue with the bundle/loading?
- because one of the modules doesn't work in node (and if so which)?

From what I can see at the moment, it seems the differences between js-data-http, js-data-http-node and js-data-http-fetch are down to which packages are included in the bundle (specifically axios). In which case, is it not possible to use `browser` field in the package.json to change the entry point for browsers to fix this?

Thanks.
