### ISSUE TITLE
Cannot read property 'http' of undefined

### ISSUE THREAD

**Issue by gutenye** [js-data/js-data-http#18]
When I use it like

```
var DSHttpAdapter = require("js-data-http")
var adapter = new DSHttpAdapter()
```

I got
```
node_modules/js-data-http/dist/js-data-http.js:140
	    this.http = options.http || axios;
```

**Comment by jmdobry** [comment]
What version are you using?

**Comment by gutenye** [comment]
2.0.0

**Comment by MarkHerhold** [comment]
I am having the exact same issue. js-data-http v2.0.0. Tested on io.js v3.0.0 and node 0.12.7 for good measure.

**Comment by MarkHerhold** [comment]
It looks like this can be simply fixed by modifying the example code above (copied from the README) to include an options object.

```
var DSHttpAdapter = require("js-data-http")
var adapter = new DSHttpAdapter({})
```

Passing in undefined as the options argument is not a common use-case though because users need to specify their API's basePath. I can't see how DSHttpAdapter can do anything without this information. I think js-data-http should throw an error if the user fails to specify an object to the DSHttpAdapter constructor. It should also throw an error if the user fails to specify the basePath inside the said object.

I would also modify the README to have:

```
var DSHttpAdapter = require("js-data-http")
var adapter = new DSHttpAdapter({ basePath: "http://[address here]/" })
```

**Comment by jmdobry** [comment]
I'll take a look when I have a development comp again.
