### ISSUE TITLE
Module not found: Error: Cannot resolve module 'axios' 

### ISSUE THREAD

**Issue by allanbond** [js-data/js-data-http#42]
We recently started seeing:
```Module not found: Error: Cannot resolve module 'axios' ``` during our webpack build.

I noticed that axios was recently made a devDependency instead of a dependency in package.json.

By making it a dependency, the error disappears.

**Comment by jmdobry** [comment]
The fix you need is to add `axios` to the `externals` option in your webpack config ([here is an example](https://github.com/js-data/js-data-angular/blob/master/build_examples/webpack/webpack.config.js#L6)). You don't want webpack bundling axios in your build because axios is already bundled inside js-data-http. If anything, making axios a devDependency (which it is and should be), revealed that you were unnecessarily bundling axios, and this should now allow you to shave a number of kilobytes off your build.

**Comment by allanbond** [comment]
great, thanks for the explanation!

**Comment by justcald** [comment]
Thank you so much! Worked perfect

**Comment by TEJAPS** [comment]
even if we go with yarn add axios , it is working fine which is not the same with npm

**Comment by sithuhlaing** [comment]
for react-create-app, I can't configure webpack how can I do?

**Comment by crobinson42** [comment]
@sithuhlaing I just created a new create-react-app project, installed js-data and js-data-http, started the project and everything runs without error. 

Here's the demo repository: https://github.com/crobinson42/demo-js-data-create-react-app

My environment:

Node.js 10.8.0
NPM 6.3.0

**Comment by mave108** [comment]
> for react-create-app, I can't configure webpack how can I do?

You need to run "npm eject" command to eject the config files

**Comment by vpaul08** [comment]
I installed axios using yarn add but was getting the same error. Then I did a yarn upgrade and yarn install, which eventually cleared up the error.

**Comment by mave108** [comment]
try uninstalling axios then install axios again. It works for me.

**Comment by dwjohnston** [comment]
@mave108  - Worked for me - some how my axios had gone missing from node_modules
